[package]
name = "evolution-sim"
version = "0.1.0"
authors = ["majorsopa"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ordered-float = "2.10.0"
multimap = "0.8.3"
